databases:
  - name: mysql-db
    plan: free # or select a paid plan if needed
    properties:
      user: root
      password: root
      databaseName: rfm
services:
  - type: web
    name: rfm-app
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-db.internal:3306/rfm
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
    ports:
      - 8080
    runtime: docker
