services:
  - type: web
    name: rfm-app
    env: docker
    plan: starter
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql:3306/rfm
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
    ports:
      - 8080

  - type: private_service
    name: mysql-db
    plan: starter
    runtime: docker
    image: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: rfm
